### ISSUE TITLE
Drop down missing

### ISSUE THREAD

**Issue by etzlers** [dragouf/Stash-Reviewers-Chrome-Extension#11]
The drop down to select the group you want on a pull request does not appear when you create a pull request by clicking on a branch in the Branches view and clicking create pull request from there.

**Comment by bkbeachlabs** [comment]
Same issue for me

**Comment by dragouf** [comment]
which version of stash you have ?

**Comment by etzlers** [comment]
We are currently using 4.3.0 (now renamed BitBucket) and should be moving to 4.5.2 in the next few weeks.

**Comment by bkbeachlabs** [comment]
We've got Stash v3.1.3

**Comment by dragouf** [comment]
I can't reproduce. Can you confirm that json group definition you added in options panel is well formed ?

And also, please check there is no error in chrome console. If you find any, can you paste it here ?

**Comment by etzlers** [comment]
Excellent!! That seems to have resolved my issues!! Thank you!!!

For anyone looking to use the new Bitbucket Server plugin note that you must configure the group (amongst other new settings) in the settings for the extension now as opposed to a dropdown menu from the plugin. :)

**Comment by bkbeachlabs** [comment]
I'm seeing these errors in the console:

batch.js?locale=en-US:1786 Uncaught Error: suggested-reviewers missing eve
batch.js?locale=en-US:2324 Downloading resources:
js!/s/71095c56c641f2c4a4f189b9dfcd7a38-T/en_US/faa46f8/1/0.0/_/download/batch/com.atlassian.stash.stash-web-api:state/com.atlassian.stash.stash-web-api:state.js?locale=en-US!order
batch.js?locale=en-US:1786 Uncaught Error: stash-plugin/header-notification missing aui/flag

But I'll try your update now

**Comment by etzlers** [comment]
Note about the new version, it appears the description for "Check new Version" under feature is identical to "PR Template" not sure that's correct? :)

**Comment by dragouf** [comment]
@etzlers oh nice catch! ok, I'll fix it in next minor release.

@bkbeachlabs I wait for your feedback after you test the new version before to close this ticket.

**Comment by bkbeachlabs** [comment]
Unfortunately I'm still seeing the same error

**Comment by dragouf** [comment]
@bkbeachlabs can you give me more information. Which version of the extension are you using now ?

**Comment by bkbeachlabs** [comment]
1.6.2. Is there anything else I can do to help with debugging this?

**Comment by dragouf** [comment]
Try 1.6.4 and give me feedback, it should be fixed.

**Comment by bkbeachlabs** [comment]
Ok this seems to be making progress. I got a popup asking me to allow the domain to send me notifications and I can see the menu option to show recent PR messages, but I still don't the Groups button.

When I installed the extension package I noticed an error is displayed in the chrome extensions configuration menu:

`There were warnings when trying to install this extension:
Unrecognized manifest key 'applications'.`

**Comment by bkbeachlabs** [comment]
Actually it looks like the recent messages pane never populates too

**Comment by dragouf** [comment]
Did you set the json group definition in extension option panel ?

Do you have anything in the console ?

Without any information it's hard to solve

**Comment by bkbeachlabs** [comment]
Here's what I see in the Console now:

```
JQMIGRATE: Logging is active
batch.js?locale=en-US:189 JQMIGRATE: jQuery.browser is deprecated
batch.js?locale=en-US:189 console.trace()g @ batch.js?locale=en-US:189
batch.js?locale=en-US:1786 Uncaught Error: suggested-reviewers missing eve
batch.js?locale=en-US:2324 Downloading resources:
js!/s/71095c56c641f2c4a4f189b9dfcd7a38-T/en_US/faa46f8/1/0.0/_/download/batch/com.atlassian.stash.stash-web-api:state/com.atlassian.stash.stash-web-api:state.js?locale=en-US!order
batch.js?locale=en-US:2324 Downloading resources:

stash_page.js:633 Uncaught TypeError: Cannot read property 'repository' of undefined
stash_page.js:913 Uncaught TypeError: Cannot read property 'forEach' of undefined
stash_page.js:913 Uncaught TypeError: Cannot read property 'forEach' of undefinedgetMostRecentActivityDate @ stash_page.js:913(anonymous function) @ stash_page.js:849filterAnOrderActivities @ stash_page.js:839activitiesCallback @ stash_page.js:1380(anonymous function) @ stash_page.js:1390
stash_page.js:913 Uncaught TypeError: Cannot read property 'forEach' of undefined
```

As I mentioned before I also see this:

![screen shot 2016-05-31 at 2 48 39 pm](https://cloud.githubusercontent.com/assets/4221514/15686531/cdfd6900-273e-11e6-8845-673976ab87d3.png)

My groups JSON is also valid. 

Thanks for continuing to investigate!

**Comment by dragouf** [comment]
Like I said, the error in your screen shot is normal.

Can you try to load extension from branch `bugfix_11` to see if it fix your problem ?

**Comment by bkbeachlabs** [comment]
thanks for clarifying the error message (again) :D 

I tried bugfix_11 and it appears to fix some of the errors, but still can't see the user groups.

```
batch.js?locale=en-US:1786 Uncaught Error: suggested-reviewers missing eveH @ batch.js?locale=en-US:1786G @ batch.js?locale=en-US:1786A @ batch.js?locale=en-US:1786require @ batch.js?locale=en-US:1788(anonymous function) @ batch.js?locale=en-US:1735k @ batch.js?locale=en-US:69n.fireWith @ batch.js?locale=en-US:70c.extend.ready @ batch.js?locale=en-US:23P @ batch.js?locale=en-US:18
batch.js?locale=en-US:2324 Downloading resources:

batch.js?locale=en-US:2324 Downloading resources:
js!/s/71095c56c641f2c4a4f189b9dfcd7a38-T/en_US/faa46f8/1/0.0/_/download/batch/com.atlassian.stash.stash-web-api:state/com.atlassian.stash.stash-web-api:state.js?locale=en-US!order
stash_page.js:633 Uncaught TypeError: Cannot read property 'repository' of undefined
```

I did some investigating in the Console, and the last error is happening because `pr.fromRef()` returns undefined in the `addCheckoutLink()` function on `stash_page.js`.

So when we go to do this check, we return:

```
if (!pr.fromRef.repository.project) {
				console.info('no rights to display checkout dropdown');
				return;
			}
```

**Comment by bkbeachlabs** [comment]
Any further updates on this @dragouf?

**Comment by dragouf** [comment]
Sorry, I had no time to work on it last past days. The problem is that I can't reproduce it and it's hard to solve. I don't know exactly why all of those data or missing in your case. Anyway if you have time to debug by yourself don't hesitate to send a pull request. I will see what I can do as soon as I have time.
